# Generated by Django 3.2.12 on 2024-12-04 08:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('auteur', models.CharField(max_length=255)),
                ('genre', models.CharField(max_length=50)),
                ('synopsis', models.TextField()),
                ('couverture', models.ImageField(blank=True, null=True, upload_to='covers/')),
                ('added_by', models.ForeignKey(db_column='added_by', default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'books',
            },
        ),
        migrations.CreateModel(
            name='Recommandation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_recommendation', models.DateTimeField(auto_now_add=True)),
                ('id_livre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations_sent', to=settings.AUTH_USER_MODEL)),
                ('recommendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'recommandations',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='books.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='recommandation',
            constraint=models.UniqueConstraint(fields=('id_user', 'id_livre', 'recommendee'), name='unique_recommendation'),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('book', 'user')},
        ),
    ]
